<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-17 13:36
=======
# Generated by Django 5.2.8 on 2025-11-14 11:15
>>>>>>> 325d5cf4f55aec66b045510537479ef535a01b24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.model'))),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('status', models.TextField()),
                ('created_at', models.TimeField()),
            ],
        ),
    ]
