<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-17 13:36
=======
# Generated by Django 5.2.8 on 2025-11-14 11:15
>>>>>>> 325d5cf4f55aec66b045510537479ef535a01b24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('total', models.FloatField()),
                ('status', models.CharField()),
                ('delivery_adress', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
=======
                ('total', models.IntegerField()),
                ('status', models.TextField()),
                ('delivery_address', models.TextField()),
                ('phone', models.TextField()),
                ('created_at', models.TimeField()),
>>>>>>> 325d5cf4f55aec66b045510537479ef535a01b24
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
=======
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
>>>>>>> 325d5cf4f55aec66b045510537479ef535a01b24
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
