# Generated by Django 5.2.8 on 2025-11-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.TextField(choices=[('vendor', 'Vendor'), ('customer', 'Customer')])),
                ('phone', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
